[[ColPack]]
arch = "aarch64"
git-tree-sha1 = "15707f9ffa171e3bf4fb82f194aa8e8d4992f654"
os = "macos"

    [[ColPack.download]]
    sha256 = "63a27f42e739c3020d82494a9e1a8e1b855274e0acb5ce5a73583eb6671b826d"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.aarch64-apple-darwin.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24becec83b229ae18b91724c926181a2d2b3cbf6"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "ef1480a5fecaa46c0b759417cef04b40c4e0d9b0940bf801a38c4192afbb3216"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.aarch64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d0e70beb681617d6a6379bee41f733a15221b72"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "d37935263974c768a5ea2eebfb2b881d1d7fc891b188ba8c473df3270b9ca554"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "439aa22f5458d66fe4750fb6755a55e81902099c"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "ba49c978b381d8568238a3650f0fcb6d1f51f2f6d5404b9a1c5ca8f0b6bc9fae"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.aarch64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d31c3f27b0b5553968ab039f7dd9ee4dd798754"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "842921dc40398ee9fac6a1f071900b2db36d0b5e9908af854719bd1ce2c0e7f4"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.aarch64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad7253d953103c1949ae5d4048793bb7f9f1148a"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "b707ebc6dafc69e2b819511ea2e746efa98222f3dad54d0c075aaa41a12717fa"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8e13911fbe826586098bdd39d2457c662538e68"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "dad74a39bcc411129acfb9d8734cc458ef0cefbb737abc9614fd763f7797f213"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f5fd987f719029c0d06b0004499151a8bef89a4"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "ad2b94cbc66d9c4a3894060fb4931a224196f226fdb2e01aee7477ba525651d7"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "763219cab6175faad137ae86a7fb47a0df3ad7d7"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "7b14c181fc7f8012a488145f67565fd69204d01973000ad7c38ff2c5c2808039"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "565384cd26879e90dd4dc1d88bf1190e26a2c74e"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "c0a5b7732371b0429879de07dfdb2cbf7d9fc582c7e640b6bb50668871deb8d7"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6af0db9ce2c3fc3b2a045d3c02e0138bc81979cf"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "08a81cfa9146a52a4ea8af6fd30fc40ab6f19c2ce5bb906cbd7023cae5a2511d"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71e160fe873172c26a6f1b0d07c60c63819d67fc"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "318cd02fa7d0ccb88a84cc6e10d8996cd49ab2941aca2d138efee9770d0ae90a"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c09299f31c12b001926580ad6c5c608841223b9"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "a00249c238dd5c98ae1fa448ddd142a12552e71f2710226d2e918335ce7e0937"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72d94db78d5f8d27bb60881fae5045a492adc6c0"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "e7cd8d42cb27509cd75ecfb20ea60a0d438b4f827cb841901539067be4c9701f"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.i686-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c92d007c73228364e7a10226b576781d227af041"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "f47fd5ff6694594d683d3182d1f1b4c03d53d7a26eb402e3585640a7e5f58cf7"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.i686-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "676a892775d05aedd3544ae4a03324e9e96540e9"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "d1fa5ed8108de2c7cc35786e104b51d877eeadee8239fca5856ba44b6ef15b8b"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.i686-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb10fc9b39e98213eacf7fe96d429254f5671e59"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "e1704e172a554f91e1eaa510976f3ce01e310a29c79190e5fb4fe87960e916e5"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.i686-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d265ca5de03006cbda9fbd2fc7ae434d2ab22a3"
os = "windows"

    [[ColPack.download]]
    sha256 = "853b5a5e262a14bed54d22ed1ff12c44a8de6aa61a9a889a9d2c56fa0748ce42"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.i686-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73eb5e07ff6a65d5633e7038c420db4c55936de1"
os = "windows"

    [[ColPack.download]]
    sha256 = "867ee56063774dd24d8c105c1bd4db0c3056ea0e4232acc88ef43f03fb2fe308"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.i686-w64-mingw32-cxx11.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20df2f589bbe4b73c2ee850ba16f7f81132957f5"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "3d8ed44dc5e55a24fe452ffe62123642b2b86bd25dd7cbe9661f3099aca48521"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a82df227470b17cbd49879d8c101b980fb9e761"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "ec0e2cebc378055c803ef1fad0f7f20b3003177be719dcad8a4909b9b133890d"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "3735184356903ddf5ab834acc3bafc3707f6543e"
os = "macos"

    [[ColPack.download]]
    sha256 = "86f5e1a40f7b75d59b2cf8d85764a4911d565a12836e1840877625d2204cfb3b"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.x86_64-apple-darwin.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9f7fcb05339416328c6051bffc3bf86aa08f35e"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "ba8fd8f420dadc98213f997755112a355d0c7529f0feb7194f421a0b9d3edb8c"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dc0661f8374a0c9f66cc35807878ca2d28baf0f"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "abc2e8f1e500356db8156f87fb9d08edb7afd20305bde4a1a46f07242ae75f6d"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58bab36723c88c3ac8c351d7f3cd9d815bcd39f0"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "bd4d95e91984a649d3a01da3536f4994150709c0866f9f120986072efabf1273"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.x86_64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae50f83a59dd68f9962507dab63ed3fe34418d88"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "143befb459d8093b7f74b7a752503a822cc874812475f1d12fee032046619383"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.x86_64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "16c3c2871d3bfe122f6d5c1d9028841ada549c06"
os = "freebsd"

    [[ColPack.download]]
    sha256 = "08932958ddbd97cb2e3160ba9ae3939e688dc05d029004d3e130cfa4ae104a7e"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.x86_64-unknown-freebsd.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cf59563204828047dcab2f99abfb11182ddc6d9"
os = "windows"

    [[ColPack.download]]
    sha256 = "2fbef34616f96247f418038b37d2552eb7f4a9771a2071939db0112cc2a1cc8a"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c1ee92077a5a6392456c81e733420ad223e94f5"
os = "windows"

    [[ColPack.download]]
    sha256 = "79255b938078bdf8e32cbd0fa805b7763b88203fd98898c3deb257df25ecf2bb"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.1+0/ColPack.v0.4.1.x86_64-w64-mingw32-cxx11.tar.gz"
