[[ColPack]]
arch = "aarch64"
git-tree-sha1 = "19d020cd46d127bf6250a7ca602d328a30f4392d"
os = "macos"

    [[ColPack.download]]
    sha256 = "53b63895ecbdbb88ccc82121289e3265afd0fba15072aee339b9d410218788de"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.aarch64-apple-darwin.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ff9c4178bf596146cc5fc1befa34a951ce20d9d"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "faa2a089fbf10cc466a52b4662c3514169948c7eee5a9edb2f79819bab66f308"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8b55801001131111c92c864f2ba092e5c1f0fe1"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "7c692ca40c73eee831b0e33630b173b5a96f6eeb0fbd7cb6008e1f758dba2ec5"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74d4f003e9ede022229be8342ceface5837332c3"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "d47c67bc6fb2d2966cb47c129d697dc5a4a97a56b12961771620aa713e44de48"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9c7932b4e665c8feede2fe50ac2ba6fae1012a3"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "99d2d9f6955c157ebe2d00dec57d3e79f46d80bbf59faf68e299c349deb397a8"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b9d96418ff16bedcbdf66e469c0524f98116858"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "07f36a76fafe95e189c865f38927957bfa1b20b3a96b642d79970fe6e5085a76"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f2c5c35d1d7200bfb0674c71c55bf61bdcf605b"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "a13037027dbecbe285c912c18bfdf30467fa606d87d66bb11084a6240a974242"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e081f2773f9127a3ba034e0ea3c48a4667c4b1c6"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "4d9916936917a34d705a6deec6cde35c9176fd8a62545896c9d88c1da3ef72b9"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cae879131a68d113ea4a8287e0410ec2f710a4bc"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "248913e79f3e3d3646f8ba68fd6253173ec72d0bda2cfb8befc51ad05067d296"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23c7a4f7f526e1adac06189935e8962a88ed4ff6"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "efb994302fe17a6b49cbc09a8cf9ff93e088123674658c3054db4a6446dd843b"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bde19dfe6975f9ab372afde711cdc97e702fcd9e"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "8ca7c45a75659a4085b3bcc3ec9b6b08b4c5acd5e4be0a2152ccaf020df4138c"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "536757699e13789ed9bd41fede3471831b14b854"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "2ec7dbb688c349bf4b28aaae2857b70db79df505d8a22757d98fe1f118c004c6"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fe68e6e1a2752244758e05b4253cce4a6a5717f"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "fa5e211b86b5387cf96e22f9ddb5061b1aa4aef12739670a560739c3f687f356"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1135547a22f7cafdbee4a3597f9e6dce71bd24d"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "67a56b432a76122c9dfd82d846a6bb116d1a7d8d1a056d9e5e61ecea474e34f2"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.i686-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "269551899db675a4a1c64f890c30990ee5c9f036"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "6dc93be7aaaf32ca7efcea01ae009d4f19a7bfedb74ad1fd7ce52cacc40a46ad"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.i686-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ce9997dedcf5963de23778b49f030ce0fa6a1d8"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "4c85008b5385e52c1ec1d7ff711f741d2708925416fb24d33bb6e89c823ddc51"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.i686-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4fde31ec10d1431c10c4e3408bfa9b12252fef4"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "4215d901c6f63d154e19a192bffa425a3a77e426da5b0adc64cac297a11b5b57"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.i686-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5914dfd49afbee1835648d2a220d81e91c8b49d8"
os = "windows"

    [[ColPack.download]]
    sha256 = "b808b9e6356c5edaa74e1cadf221e3c321a730fb7836eddd43e7d2eb12abad9e"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8221f554dcbc44b0301fa7c0a62bd2d4bf4198e"
os = "windows"

    [[ColPack.download]]
    sha256 = "d40dbb4f5c69e4b5389d99420a808d17a587d1368e793478374d22b5dfdef547"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "587bef577ea26f8338a4acf7399fdbad52cfb63a"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "687b953c2402fa7a1ca418973a7b4520b9c497b625ce67f6cc6572d9d07fcfe8"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b74795de4018c18b88699f1a88923e251240404d"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "6a6104f834e125430e4aac52976c29019b1008de992adeebaad1ca393573e30a"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "63c1bf7297702a2ccbaed29b39bd010dd890324a"
os = "macos"

    [[ColPack.download]]
    sha256 = "57193007a65fd181dcdcce9143fd62fa659c53a28555fa8d0ab00d264c601c84"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.x86_64-apple-darwin.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb6feab9417921e708cc0631e73c9db7983c593d"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "c34c4acd802e62761b3355432aeae6295ccb94ae8297399d6417725de79bc354"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "749aa8b3dfc38d22523cc3454ca7f13296257dc1"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "01452df044844fe3df20ce7854af73a3eec021c6fb8def423c28d369c94d9ca1"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a218a91243c0ca532fc8126aa58b25bba36b84c"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "6d0f39868f111746106eefea51946624c557f60b8b22583bef11aebca4b08433"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cabcd34846a22619f782ce6661e1c7bd66213090"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "d28e0c72d6bd98cfae3ea458417da74d00c8905d88a479a087f9b7aff774e93c"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "2647077975f27590382fadb04ead03d130d351e5"
os = "freebsd"

    [[ColPack.download]]
    sha256 = "ef3995888faca23055e29459271bf26a484da531f2912f632eab959f3df88703"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6edb229d3e7cc17e157f98e647dd432ddacb09e8"
os = "windows"

    [[ColPack.download]]
    sha256 = "462aaeac2aae5e22cef128edf0f14c79d1566fb557ec59d3ca02258ab49e80fe"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be884f984c0b2ed4e1c8bc28d82259e5a54da545"
os = "windows"

    [[ColPack.download]]
    sha256 = "053c8a62e0d0dfe43d51d9d2d959eff2556bb69d600b44c0c42b83b60b4b0bf0"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.2.0+0/ColPack.v0.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
