[[ColPack]]
arch = "aarch64"
git-tree-sha1 = "680af11f2d0ae3b5d6643f412bf64073be40964e"
os = "macos"

    [[ColPack.download]]
    sha256 = "8a2b87eb344614d71540cca81f276397dd81534fb1466fb1203f1bc1cff557d7"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.aarch64-apple-darwin.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e25ef4f051d111914770f7a1de46f6405f5f9b4a"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "9ab405b9e806627b27729e32ea1d9b65b6dc7620508b93bc3a3914b52e8e9635"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.aarch64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99523ea092466ea90b174a9d7e54eeb45f2b5620"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "4da82995dbbc99a5def577966c8c38a279339a4f9f0841ddd193ce7dcc8be005"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2492551153f8a40d46579055b52d63456eb4f83c"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "f5449169db596325da1c0c11bce3ff09d0215d2ee6c9073f363acaa7e0e43c64"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.aarch64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a0768d387cb60fea91274e196e4de2b63029e51"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "c8d8457ea15ef0bac19cc1fe4ddae27363257846fb0eb1b830b20b45c589f9f9"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.aarch64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "aarch64"
git-tree-sha1 = "c688343b43d4bcb6af07014f58f51b5897389974"
os = "freebsd"

    [[ColPack.download]]
    sha256 = "d2cff3a5b45fac181471d1e6bdd3361b771d783e2cad5be866e4fbb84f89e2a2"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.aarch64-unknown-freebsd.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa2224a497a508d17ef3e4fce29219b25b203af0"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "30211a0e9dbf1a9249a41d7253c46abcc8643caaa919a0913a07f22755c56404"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e81bef327709891ef2222413acc2c55167f102d"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "688cf08fd75eb7640cfb22eaeb9ea253e490bdb1b6c85223f0c581d6aa70471c"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b8c17fd60e0d7e70d19e9265f3ba1e4c7dcecb9"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "ec42116e8f9a54df0815a65b1ef471f67974a0d6345e678d5f6155d6593acbd4"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20879e88d1f5c40b8ac9b0a2237722d6c33282a7"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "eade437ef050247b9a7370bf576637750ca427668155b316f04120ffdc647a6a"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7501b1a8700b440f1aebad82e1018375959804c"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "4789cd8df6d059d723b04c99e982d723570d5b8e952c82e9fd2dbb7b0ba44e9c"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbf305572a091f335492944e1be400e48dc98d9c"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "8c43da28a9c143ed51c75237ed776dbea8b76318ed55c30e754a54bddd1e3e5e"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d8b874815a2a0f1c4547eb38c80ea08cbfdfea8"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "18d5eacd177a055ab9adb9574c3ac47834e16f70cb9eb5babc2357d9569efa30"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b2b1710602d4aa5e91cfe5f37f75e3bfa4e89ff"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "e5fb538840f5e43e4fc882bc4d6eed5dbc663a95baad2691ea0339c4b6b9304e"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e08589697c70078f8b530aaf738c2659610e2f94"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "20b3d7f23b56c82a9e3e79e31021b1bf698f38da10ae0cde7c8859dc936d8c20"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.i686-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2530717758cf0cec3b62c8be93e89131ef671b7e"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "704855fdae42bdde90ece71368b6d9ca239edc1d29128bf7ed95a289b4b13033"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.i686-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69dd2648a058da184922c712f7287d6f581e30c3"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "ea6e75c68e30817f7a560d040892300c8bccf5866b39f8601664318755db0074"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.i686-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d959ec622534fa7fc213b852ef96261ba74cd73"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "e51561c420c6f912221e59eb3252faafbead2a4921e7b387c3eb8ab79a6b47eb"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.i686-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dca5a606f296c7351fa893e1e08cc51a9db9598b"
os = "windows"

    [[ColPack.download]]
    sha256 = "a6f6c92a8fce035c2ebdf854ec823c6a2271b490cbd246956d9b0d90b59ff05a"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.i686-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ee6e8534cc94d1087a27943008c461322be7ffd"
os = "windows"

    [[ColPack.download]]
    sha256 = "92323a42fb00c9fdbf4bf733b2d391b687dfe017b402c3642d4acdfd407b8eeb"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.i686-w64-mingw32-cxx11.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ab710c637777dc2d45e9ea54fa24f62d177bba8"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "0b684727eeb54461e00a5b202a2cfbb129bb8b4e0f3ea5bb7480e9baf9db9439"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57bf6cc1f67fedf744dd04e128a12969f5de722d"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "82eefa3a8e54d679c84d5e6b5078ecef836a9d8d4124bbdc6527f7833239fed4"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d37c25d7c137a90936a456cd1d25dfbad9fada50"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "158f367c968c9f11db85ad14ca0caa5b1fe721c39d17b3cdfe6c7253078d3541"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.riscv64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d75f366b70ca5e973a2a1946c7e53a45bfc51a6"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "db8105889633648af267ce98ee926402e7c67472b1e86b085f6d31fc127666af"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.riscv64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "665548b7ca51b73a5f1f267dffc0f077a9db4453"
os = "macos"

    [[ColPack.download]]
    sha256 = "b4365e310a06eb56686ee1d0c0574c74146bc3abaf56bc44ca390e271ff9acd8"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.x86_64-apple-darwin.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79edbe6c18ebdb2d47bccc145ee1d2c4e48bb387"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "1cbd19bc72feddad78b9cfbde1581e1e4a21606b23121c84daa83263e7dcbc01"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.x86_64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44707143b77f1c66e28c9f1e58c72fd008575eea"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "7de731abeff457fa6eb3f862d3a0ddcad8e4af6bdc28a14b345bd3dfc07b210a"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c983a9271e333228f231278b41293069a27e5500"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "bc1fb303c6f48f0d1f3f4651594bd02a54d75f4f9a839a51a2c38fc7b54fd888"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.x86_64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb2d1aa1a8b1d7a31d4e8f9907ce1cda2b152471"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "8602a3cb236db955d1ae0e8a135f9f79236aefd0b608a1a591c71dd14bc62177"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.x86_64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "80b9769ef9be8fbf1912e404de84ea0d0d7ebbfe"
os = "freebsd"

    [[ColPack.download]]
    sha256 = "607503c0d3289141ae3de56820f09e45b35b3649cc28e25890abc0396d0f3f3b"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.x86_64-unknown-freebsd.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15c2781a868079982f3dd6353111441f7e3eb3a2"
os = "windows"

    [[ColPack.download]]
    sha256 = "2967a51a0d4baf5e0938623f4734de646bb60a56bc6210714b9059828f9d4a91"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23fcfbb4f4f239eae725fcf4fb4ee940e0471113"
os = "windows"

    [[ColPack.download]]
    sha256 = "062cac71272393110d0083d3d73c895b37879180ec5c275144fd3f436cebf066"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.2+0/ColPack.v0.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
