[[ColPack]]
arch = "aarch64"
git-tree-sha1 = "96e9bb37263eb2b2b07af7bc5e524c94ef1fec80"
os = "macos"

    [[ColPack.download]]
    sha256 = "5c22ec0e8cba8e7a8dde3b72659235dfbe9fb6a7b0ae06954ca1d083ae03bf13"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.aarch64-apple-darwin.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd1950648d968b6955fa4f6aac336bcc71e44517"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "e7ba7cc10b52bf2fe61aaf57cbe37d0b4f9c0a4d5c2363709cd28aab0da28b94"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.aarch64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7236128ccf01e71894fef4ee2e985b1ff37afa2c"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "7303a08bcc7fa8a7850e89415f9c2ec046f0d69d1295434d2e586a7cd3971762"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.aarch64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbf736bc3685ae114533dcdd5abefa85abf14264"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "9b11a19c1ad5d246fb4d8015b39f978dc211f44ede106d4480a1515d77341d76"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.aarch64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc1bd7f11df3baac365931cdb13fbd046d1342d4"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "2908179203dcbd0b77a7d312774dc7d81976e55c205546e2d9c0be6e44eaea01"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.aarch64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "aarch64"
git-tree-sha1 = "e9d8436fe077d1126fac77579b51b6a625397617"
os = "freebsd"

    [[ColPack.download]]
    sha256 = "27dd9f00f875dec8976908cff1ca285e5d6e9f010d45051c28a871a8e2e5d3c6"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.aarch64-unknown-freebsd.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "979e33a6dda8ce46b8734cf9207f65ed048d84bc"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "e5fb079631f29a3424e29a3c676e2ee542a35f190bb517a339d2dab9472b92e6"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f38bcb4e2b3122cabb635aa2dd0feaedcdb8a4c1"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "d30519fe782bc27e04ed308a9dee496eaaef69b6cd5dab3eee0ff81be5746b56"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a982eea399183ca142c517e90ed1dbf97c31cc30"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "6d09aad7bb6cf3c456a17d7809065ddd43eb76d5c8c4a38cde1a1719464569b1"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f49dd62383434ab29a164284bff36a02887a3eb5"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "157af0760945ea94213d4f084f4b920099b3c0ddb7e0210c8e499fa28f0b06e3"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a79a5c67130a0541961bc42dc9f26727b4c610bf"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "43cf2df4815ba2b34fdd38b3894bfe89a5a323e0e3ca8ea50ea746e734f2b048"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da5e3064eb4eeae44288a6cca7ce289777edae1e"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "ae4aa11cb2fb41e358460b575901ceccad06e7e064ceb43e950d3a0f12bdd469"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab1a2c421ed265567e98b5e1578a4380b6e464d8"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "a98b13c610926f572cd71c6ef38b6aa336aa0daf470e92b78dac198717a3f784"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9b8d36d355081b039446e9f73e67f66e0a1c197"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "090057d0754f7abd9a9e594e153e175d997d8beaa8d610218c416340dd7a14b5"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "122b65530ac856573768f26333be77df1ba05482"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "3db356a68d7cc7da93bc6d3f48234675c03415086fe4cb20f904677f4b94acce"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.i686-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49f6d33e878a2b4311357f7f3da5ee02b124a56c"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "b95a13e9b1cc11d5eda3b9680df35c1f05124890f4ca924a0e1cb27e20479c4e"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.i686-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a3a5c799634091354bd57633a9196ac3472c0e2"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "8c6bc79185738d100526e3b758f4b38134d9d332968390ac910eee1dcf9f408f"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.i686-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14259ceb8090ebb7803b85d028bce5b65a9feac9"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "be0034a357af4a33bd0724618fe8befae71905207179e23950a4b9808b86c6eb"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.i686-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "def32adb4d6b377e8ecdcc1e4f5e9797324ca68a"
os = "windows"

    [[ColPack.download]]
    sha256 = "42d5a46aadd80013e5dab62ce31b5dd59da00cd66574061a3d94359c914c3c46"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.i686-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33652f6e96fcc23948d597fd3e81584b8d49f763"
os = "windows"

    [[ColPack.download]]
    sha256 = "46a41ca72501149ac173e4f7b2e297ceb0823e71ade9f4b625eb73d025951bf1"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.i686-w64-mingw32-cxx11.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4908b25ac516f637fb9a89a6c8bb75514d98f9a"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "ad82b1655f5e04acf6370a2e25caf9a628fb05d76ef800ee1c02afd39f09ba55"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1189c7d2c8f4763f4cfd3ae89f90045380e5b9f8"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "7b2f0eaaf95191f0a1cbf4caa557c2eee18f464fac3a6d9bb2d321a8a056f588"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90f5b3957056773ab52ae4149c6ad3b6c465cf0b"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "0865b1cfc393c665e91316bc02a0f9449d011759ee18dd4ef20c1691747da3d0"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.riscv64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1361b8c2b70d9c8cdd18e89d353a536795bb0c1b"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "cd6b13d2c1480bc442bb596faac1d1bbfece9b9eb0b40fa004851fc307508144"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.riscv64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "e2069769c75566c0642225f6605535c0b9468357"
os = "macos"

    [[ColPack.download]]
    sha256 = "f7fd93a06354779e07364aca2c2ca85d2121bc9cea8b507bb16903ba956d7eb0"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.x86_64-apple-darwin.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1181ea17628c645c77c2c1700ce8d98b48b3e820"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "13a457e2fe3737b87587ab14157034ae553beca643f3f3dcd6e185bd1f28c0fb"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.x86_64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b67e35031f029823136202bee346115d7adaf01a"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "a17f3907244ef2816442f69b042f08b0ec4bab4483ad5a34bf5faf4c3792d280"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.x86_64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6acc3659120ad0d3ff68dbceefdd8088284d36e6"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "3a069b2bba8753a3ee0686e3347b2f750d881fcfcb8f4cebfedc5507f7fc73f2"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.x86_64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81cf0a08fc61ea64c6b6544d6183360755feaf53"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "30f9a3a47e45ab2318a601eb5025816fc2d9079dbf5609305d8d4de5f9d10286"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.x86_64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "df3d15031d32af81fa4f83821d130b98bcef9f36"
os = "freebsd"

    [[ColPack.download]]
    sha256 = "e7f988b07e976414652824317fcf264eca44232385428aeafc1e5de57ae1b2eb"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.x86_64-unknown-freebsd.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "118576714d42d5d70b12f1fd110101cc80a37801"
os = "windows"

    [[ColPack.download]]
    sha256 = "5d7ce74a2e3d96a2ea808eaac1bde569222f419b1a4184a436ad48f1b6c4b934"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a08b90af927b678bbe88f46a616a256e30708a7e"
os = "windows"

    [[ColPack.download]]
    sha256 = "b094a43627af919937ea1564e015d7c26a314ed5b35f0dc07db7307575f7ae81"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.4.3+0/ColPack.v0.4.3.x86_64-w64-mingw32-cxx11.tar.gz"
