[[ColPack]]
arch = "aarch64"
git-tree-sha1 = "683d28d8b2701c977a6c7975d99ecb5ca2f1262e"
os = "macos"

    [[ColPack.download]]
    sha256 = "7856b05134840adf15d8bfd24bef0a52f610bf6c62566bda7e2f139ce76a9c49"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.aarch64-apple-darwin.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de569440f54ee3d051d8c3e2709d3cf9f0b924e2"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "88f5a75f6c51ff90a3410998a04f51e6eb44429a79ddf9a14926873de1a9778b"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eceea01812de0a64c423f926b5d51f103697cf2f"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "da4f6bc5f8c576c8bdf526ab0094669cdf9563b7da840eae9fb1200fb4db03d4"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20e4b593bfede2cf338c60dabe01117f59d79e94"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "08aee95a149cc251f016f4ad7af7b7e1f3953371b6e4358259edabc5e1f33bb2"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6454d5b601abe8817f6b09f384523ac14ee75c9"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "0bf909e28aeb3c78f602196c1071bf7ed646b8a0400375d9d9aa072c24625141"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f990f0c52cee0a0dd9b0e853d1777e982f3c878e"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "800a190d7bd152a490bfb55fe4816681142697cfc03b1bb1bf22ac75c940d6af"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc0fdc1909b254d109ac5a0a473d5e330001e670"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "b1c2f1cac758354104f0f42407872e83a60fbe8a298a7190c0212c14eed0ca18"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa333021450c071257d001fdfc3fb03eade17e10"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "c42fdbe1eadb6b65860457df4380f8d279b3c95726f960d2e51222f63ad13735"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d144eff99451be5975d0454348e581fad4a737b9"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "f9659d7849b6b901a973660d532185bb37375f7fe04cf56f8852e72e5a7222bc"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5103ab039c98878c45dab94b7bf19164f59a205"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "410163d174c3918f72f2dc0cd6d1353ebe301c631d479dc1c88f4122fcbacc74"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23ff2e6b5477d08090ee0f249676da131c113921"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "433cdd80b3f20be4ebfa57f43e770754bb4e7d3a7f7b56da83d34d4573daa03c"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c54b8cac46cf57b818d9d799eb8bc1035ff3e80"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "0df22a7fc105c79836116b01e6925b3ecd6a553992b67c300538e9777eb0715c"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a2bdfbcc27b6f63e303a89f12db4bb714d64cc4"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "eac667c88352adf3eb061a113e6b2c2bab1dd2b30676b00e21f7f30d41e19d39"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c57581761582eb9f431a49eb44d0ffd641cfc71"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "a9eb82a4877fdbbae87dfd46751e0d1eff85395087c639b55bacddaef3fede6d"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.i686-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74b7b3133c5744b101b987b1e70858ed71c79da9"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "29fbee9ad9677c6b31cf78a82133d02639fc9b6982f77cf2f311b560f526d4c7"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.i686-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdc8bb229a784044c4d4c9e5c6433a9b1fb76240"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "3617faf53775403c540d7f19465338ad09afda23b5514a47abdec214de84ef12"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.i686-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4191ca11fe5e6e787314a53d041a5041c252484a"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "7e3a948f87c7de682ea19b8bb84a36bac9ea536eac66780e53bf84ed9a8f3caa"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.i686-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a174393fdb00414ba93899108395be5742e6f288"
os = "windows"

    [[ColPack.download]]
    sha256 = "d78a2d6cca5679b6f86f0c6edac61ef0604ae30f99f06c05b1034b2b0242c67e"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4624c94dadfbf591ce36aed78614a590bdbdd256"
os = "windows"

    [[ColPack.download]]
    sha256 = "0b53331d3377914bbd9cee5c556d352a055c91d043409296c1f292f093388c41"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abaf78d588636db0c42385c494ec77650bf3d059"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "892fd38aa0751cdcc948c7cd0461e00d1c395649a9dc994e8d5f4f8113ca7be1"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "888155fecae51cbac6a46fbea59a6fc4db82eca6"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "ea5340ee580ca090ecd328f12f8f0c4b8e7b33f513d6f0d223fcf53f059a2d30"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "c7dfd814ff3b99c4b1e1b5d71d27b9ed436b649c"
os = "macos"

    [[ColPack.download]]
    sha256 = "565ec41a631e2286408007b32bfdfce625ac01526cc1793e04af7e8267252087"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.x86_64-apple-darwin.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8d7accfce021542355d3df038f9f28fc15a96cc"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "5efad715d8cd60459ac838dd67ee88d7ef77bfe2661683a52fa8bba8ba0cf6e4"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34884cb0a6c80e694feb5e626f54dd26d1a4c3dc"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "c678c27c61ef01893c8178d21e593f038c9febd4fd1b432e0df6a1b3474da327"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef7c5dd6c6850f7e75cf17cee4cd363e5cfe57ea"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "beff38c11811be717485754bfdd87c27928cf388dc16e72d0137739b4ee59677"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa11c1fd2ef741adc3977ee625c3cc5d0059e12c"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "15cd2cc6b86a4a459c4987bf910285bb8a84517754edae42f0c4ac066de5c521"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "85c4dd9a87aa65f06b80d75c51e6fcc873846249"
os = "freebsd"

    [[ColPack.download]]
    sha256 = "fbcd653e373d8a14be22143bca4eb732630ad696b9b4f6cc5badb82bdfba5a20"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.x86_64-unknown-freebsd.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5dc128fa84258d869ded57ec36e7fa0440e905a0"
os = "windows"

    [[ColPack.download]]
    sha256 = "39c365ca028557f33f6470b15ef054155f9a5ac2ec4af5095941e877d2b17ad1"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0310fb94be9ef1aaa9f015759bb79b2896eee8d9"
os = "windows"

    [[ColPack.download]]
    sha256 = "85c0f124bf94bbf114f5d411fbee91b414a657177b00bf4632b83e2e594ab160"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.3.0+0/ColPack.v0.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
