[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c9deeb35bece3b973abf33fbef6b2db5ae9e0a5"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "e71493abe77bbafafce41e2c6a8572309159116cd2f95438f5a9057bcb2d36bd"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbdc2c628f419bca269ef3892563ed760920bf91"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "7b98544da47732303fe91e7ba8279eee9bda45562b9fbfc43d1b832e40c04699"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76a7ad6d4138596f152b68725be67775ba6c00a8"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "18fb84cd1139ae79eabde9098163445f6f1c9baccee98150b9c36aec5c7631dc"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3902f63de8a241e5e53ccdf3deb925e9c2d593a3"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "26bc76e74efe8cd83b23139a2f0ebc2147d5a8fef1e2359860c4af07146ed31b"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9b12366aacb0a9b90f840773af8c82c9d97d89d"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "27715a4711297ddeb52a63c89b60ffdbcb6bb3347dc4551da829ba3c94511493"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9641182e598b89dbac6f056ee33920530e98acb"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "03550ac8fd03edd8e41001f92160904f0dc8946f4badd4aa0a4c70bc86425c04"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b51aa7c40540c44c06a43ced5e2f34ba0b7c4d0f"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "0c8f12a682ed17988cfaf7a9945d3575647a0f72a5208ab82e96b38ce7ae0fb4"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57368956cf55f7d7844e05a64778a876bf24b908"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "752d48238175c1838f195d62256c9e1ee0a7ed1a7a1b4ea21c8ca8784a387965"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e9565c145e169ab3b381a4b1be8950f9d373333"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "06773cb426f2d91dfd89dd18d66958aa70da0fec5eed21650bcb2bb34c489bbe"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6a3d6497f962a7caadcf6dc8dde067c7e8ca8f5"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "3ef47bad2b206c85b62ef6b530256ec15ea391cd12d020f61ec8fd5d33f58394"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59e1029500d75ca17310aa7cb02afc0fb64c4c75"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "5f0baf5b48ba36bbcce99977ae02440ae1fca1a720bdd3d1bac38e35fbf6d849"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0d07835eb0e8682d62b77444d9a0b82c594e0b4"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "13bf3495e30b39c8fcdee4be481d86ec952ddb0ec73cab58d9969262efff10b8"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5cc78ab92dfcca053e445b62fa74304ce59c213"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "10140d087b70ef2f4c915293413529bb5248963f1dc075a03925815fbf6ccb58"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.i686-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba6df1b14cf82e354692cdfa8d68b57e00b94d67"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "b295f45847a05666220d87d79a780fadc26ff5c33ce93cf4739d5e80df27b796"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.i686-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2b7e2e0632b3e8d027417cea962643328e0ecd4"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "8186c0e98d1e9280a15c3ce2b9899d1e3855f697c54c3c01c68a82b43442d19e"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.i686-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd489e046959fe890e3e99690c57ad7b9054fb55"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "3bc82d37c0eca796390a5b8d2904be8034c4c995b9a2c18d50e3ae91d87fdf6a"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.i686-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5d57473d90f316bffc57694fed2fd03e34c7a67"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "1184a6064c4a1842e7b2a3ee7d5da641d906755738c188fe6e5928aad2860fc7"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ff3f19cb8b2eaf319900cb109b7f75aa6ed7c8d"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "dda47d82de97faa8de8e18bf107a64ddf688a99e4611ccdf9d1063f0219c7106"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30a0840fba6170fd6532b23273e7fb5584c8f762"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "d3cda4e049e8d6744734e9a4775794568e3dd09968e5ef3120d1a75f3a65ec8c"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f750384e17c68b1f0179e37adf9161788872d081"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "a77fd6fe2baa31fb90eb3c0f2cae3f36230a5cf8a055403b6dc3a65300297ec3"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dab8524a92617f682a5885f4c5d9af8ee24fbf72"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "0c3a7134e35677d034bfd2e2cd614b1ca14da28f4c5db23add00775a84411a8e"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bfb742be90389c6d5a20d54defc892ab0ec99f3"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "87e0bff24b6f2bff68022571a173aa7ba67111e976498ae53a97ff2eb8d41cfe"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "324b18e94ceb95ff8af57f6295cbf99d658e5230"
os = "freebsd"

    [[ColPack.download]]
    sha256 = "8ee611394092ee047f75bc2b049799ce7b64df6eef9afa8a8383b2832874253f"
    url = "https://github.com/JuliaBinaryWrappers/ColPack_jll.jl/releases/download/ColPack-v0.1.0+0/ColPack.v0.1.0.x86_64-unknown-freebsd.tar.gz"
