# Autogenerated wrapper script for ColPack_jll for x86_64-w64-mingw32-cxx03
export ColPack, libcolpack

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("ColPack")
JLLWrappers.@declare_library_product(libcolpack, "libcolpack.dll")
JLLWrappers.@declare_executable_product(ColPack)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libcolpack,
        "bin\\libcolpack.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ColPack,
        "bin\\ColPack.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
